name: Bug Report
description: Report a bug in the Lithuanian Road Information GPX Downloader
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have tested with the latest version
          required: true

  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Type
      description: What type of issue are you experiencing?
      options:
        - Coordinate/Geographic Error (GPX tracks in wrong location)
        - Download/API Error (Failed to fetch data)
        - File Generation Error (GPX file creation issues)
        - Build/Installation Error
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Check output file '...'
        3. See error or incorrect behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14, Windows 11]
        - Go version: [e.g., 1.21.3]
        - Architecture: [e.g., amd64, arm64]
    validations:
      required: true

  - type: textarea
    id: coordinates
    attributes:
      label: Geographic Information (if applicable)
      description: For coordinate/geographic bugs, provide details about the incorrect location
      placeholder: |
        - Expected location: [e.g., Vilnius, Lithuania]
        - Actual location: [e.g., Abu Dhabi, UAE]
        - Sample coordinates: [e.g., lat: 24.5, lon: 55.8]
        - GPX file section with problematic coordinates

  - type: textarea
    id: logs
    attributes:
      label: Error Output/Logs
      description: Copy and paste any relevant error messages or log output
      render: shell
      placeholder: Paste error messages here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other information that might help us understand the issue