name: Daily Update

on:
  schedule:
    # Run daily at 6:00 AM UTC (8:00 AM Lithuanian time)
    - cron: '0 6 * * *'
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual trigger

jobs:
  update-gpx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./cmd/lt-road-info

    - name: Generate GPX files
      run: |
        mkdir -p output
        ./lt-road-info -output output -verbose

    - name: Upload GPX files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gpx-files
        path: output/*.gpx
        retention-days: 7

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: gpx-${{ steps.date.outputs.date }}-${{ github.run_number }}
        release_name: GPX Files - ${{ steps.date.outputs.date }}
        body: |
          Automatically generated GPX files for Lithuanian road information.
          
          ## Files included:
          - `lt-road-restrictions.gpx` - Temporary road restrictions, construction zones, repairs
          - `lt-speed-control.gpx` - Average speed control sections
          
          Generated on: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false

    - name: Upload Road Restrictions GPX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/lt-road-restrictions.gpx
        asset_name: lt-road-restrictions.gpx
        asset_content_type: application/gpx+xml

    - name: Upload Speed Control GPX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/lt-speed-control.gpx
        asset_name: lt-speed-control.gpx
        asset_content_type: application/gpx+xml

    - name: Update latest release
      run: |
        # Delete previous 'latest' release if exists
        gh release delete latest -y || true
        
        # Create new 'latest' release
        gh release create latest \
          --title "Latest GPX Files" \
          --notes "Always contains the most recent GPX files. Updated daily at 6:00 AM UTC.

        ## Direct download links:
        - [Road Restrictions](https://github.com/${{ github.repository }}/releases/latest/download/lt-road-restrictions.gpx)
        - [Speed Control Sections](https://github.com/${{ github.repository }}/releases/latest/download/lt-speed-control.gpx)
        
        Last updated: ${{ steps.date.outputs.date }}" \
          ./output/lt-road-restrictions.gpx \
          ./output/lt-speed-control.gpx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}